language: common-lisp
sudo: required

os:
  matrix:
    - linux
    - osx

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=ecl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -e '(ql:quickload :test-ci) (unless (print (test-ci:foo)) (uiop:quit 1))'
