language: common-lisp
sudo: required

os:
  - linux
  - osx

env:
  matrix:
    - LISP=sbcl-bin
    - LISP=ccl-bin
    - LISP=ecl

before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update -qq && sudo apt-get install -y --no-install-recommends libsdl2-2.0-0 libsdl2-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install sdl2; fi

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/release/scripts/install-for-ci.sh | sh

script:
  - ros -e '(ql:quickload :sdl2 :verbose t) nil'
